### ISSUE TITLE
state not available on taht api and makes functions break upon main call

### ISSUE THREAD

**Issue by tHeStRyNg** [CryptoWizardsNet/poloniex-triarb-new#1]
Hi mate hope all is cool, just a quick one on latest repo 2024 (course material) i think api changed , still didnt fix it as doing course but will ping an update and maybe if yo uallow a PR with fix later on maybe you consider merging. Super Hugs. PS Awesome course content.

root@flash1:/opt/ctw/pf-0023/poloniex-triarb-new# python3.9 main.py
Retrieving list of cryptos...
Traceback (most recent call last):
  File "/opt/ctw/pf-0023/poloniex-triarb-new/main.py", line 68, in <module>
    coin_list = step_0()
  File "/opt/ctw/pf-0023/poloniex-triarb-new/main.py", line 20, in step_0
    coin_list = func_arbitrage.collect_tradeables(coin_json)
  File "/opt/ctw/pf-0023/poloniex-triarb-new/func_arbitrage.py", line 17, in collect_tradeables
    if coin["state"] == "NORMAL":
KeyError: 'state'

**Comment by gutomaia** [comment]
+1

**Comment by Liiuc** [comment]
+1

**Comment by Sourav-G22** [comment]
### **Issue Solved**
Look into their market price api ..... In all data objects they removed "state" index key, that is why you're getting the error.

![Image](https://github.com/user-attachments/assets/7d99615b-6cad-4e59-9791-b73e76d24e37)

Please try to remove/comment out the condition in func_arbitrage.py this file at line no 17. It should looks like bellow screenshoot: 

![Image](https://github.com/user-attachments/assets/b96d4073-72ef-4424-95fc-d09f192c9a6a)


Thank you in advance. Happy to help.
